### ISSUE TITLE
Armour Enhancements Don't Work

### ISSUE THREAD

**Issue by Godsassassin007** [Stexinator/TheWitcherTRPG#10]
The armour enhancements button doesn't work. When you click it it says that this is no enhancements available even if you have magical and no magical enhancements in your inventory.

![Bug](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/6fb4c8b9-eaf3-438c-969a-3c8c2d966117)

**Comment by Stexinator** [comment]
Fixed in latest release

**Comment by Godsassassin007** [comment]
> Fixed in latest release

Thank you for the speedy reply and fix. My group and I greatly appreciate your hard work.
