### ISSUE TITLE
Armor Enhancement Resistances

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#100]
You've added new Resistances to Armor to cover Bleed, Fire, and Poison Resistance. Can you do the same thing with Armor Enhancements (Core pg. 90)? Fiber has Bleed Resistance, and Hardened Leather has Fire Resistance. It may be beneficial to add these to Glyphs as well.

Additionally, could you add the options for Immunities too? Right now the only thing I know of that has an Immunity is the Wyvern Scale Shield (A Professional's Tools pg. 8), but it may be useful for GMs who want to create their own Relics or homebrew something like Draconid Leather Armor (which isn't included, but is mentioned in the Corebook on pg. 307).

**Comment by Siryphas** [comment]
An add-on, could you add Ablating, Armor Piercing, and Improved Armor Piercing to Ammunition and Runes?

**Comment by Stexinator** [comment]
The wyvern shield does not add immunity to fire. It just prevents reliability damage from fire. Unfortunatley I have no idea yet how to add it. As long as this is the only item that has it, it will be low priority

**Comment by Stexinator** [comment]
> An add-on, could you add Ablating, Armor Piercing, and Improved Armor Piercing to Ammunition and Runes?

Can you create a new issue for that? It does not fit the title
