### ISSUE TITLE
Armor/Weapon Descriptions

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#101]
Would it be possible to add a description box for weapons and armor? Not only would it help describe each item as it is from the book, but also each of the Relic Weapons and Armor has a section for the story behind that Relic. It would be nice if that were something included with the item, assuming they beat the Education DC for that Relic.

**Comment by moliloo** [comment]
Writing in weapon description the text is saved without problems, either creating in the sheet or in item section of the foundy, dragging to the sheet the description don't desapear, this feature is fine to me
