### ISSUE TITLE
New language skills under INT?

### ISSUE THREAD

**Issue by graytolga** [Stexinator/TheWitcherTRPG#106]
Can a custom skill be added under the INT category for the purpose of creating a new language skill? The same thing can be done with the Performance and Fine Arts skills: removing them and instead adding custom-made skills (for painting, writing etc.)?

**Comment by Stexinator** [comment]
This has the same problem as https://github.com/Stexinator/TheWitcherTRPG/issues/41
As long as there is no UX solution I wont start implementing it.

For now you could try to do it with a module if your skills are known

**Comment by AlexanderTheGr3at** [comment]
Issue moved to new repo
