### ISSUE TITLE
Igni Damage Button Doesn't Work

### ISSUE THREAD

**Issue by Godsassassin007** [Stexinator/TheWitcherTRPG#11]
When pressing the damage button for igni it doesn't roll or display anything.

**Comment by Godsassassin007** [comment]
I am able to get it to roll if I remove the /STA portion. But then it only rolls 1d6 no matter how much stamina is spent.

**Comment by Stexinator** [comment]
Currently the system does not support what you are trying. If I get the time I might add it

**Comment by Godsassassin007** [comment]
> Currently the system does not support what you are trying. If I get the time I might add it

That would be fantastic if you could. If not it's all good. Thanks for letting me know it isn't supported. I'll have them roll it manually.
