### ISSUE TITLE
Status Effect: Healing & Upgrades

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#117]
Can we add Healing and Upgrade to the token status effects, so we can track the number of rounds tokens have of healing effects or upgrades, such as a spell bonus or a Potion's effect?

**Comment by Stexinator** [comment]
The system does not support multiple level of status. Currently it can only be marked that healing/regeneration is happening in some kind of form.

Does that satisfy your need?

**Comment by Stexinator** [comment]
For bonus stats from potions etc you can use global modifier. Soon (tm) I added activating them from spells and items on the using actor

**Comment by Siryphas** [comment]
I have a module for stacking effects, but the effect needs to be present in the first place. Having a Healing would help even without stacking to indicate Regeneration from potions or magic

**Comment by pedroaugustobt** [comment]
@Siryphas what module do you use?

**Comment by Siryphas** [comment]
It's called **Status Icon Counter**
