### ISSUE TITLE
Critical Wound Automation

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#118]
When Critical Wounds are applied, can they automate the penalties to both PC and NPC/Monster Sheets? 
I.e. a -2 to Dodge Escape and Athletics.

**Comment by Stexinator** [comment]
Currently I am working on auto-detecting crits and prompting bonus damage and crit wounds. For this critical wounds need to be reworked and then this is also feasible

**Comment by Stexinator** [comment]
Simple
- [ ] Cracked Jaw
- [ ] Disfiguring Scar
- [ ] Cracked Ribs
- [ ] Foreign Object
- [ ] Sprained Arm
- [ ] Sprained Leg

Complex
- [ ] Minor Head Wound
- [ ] Lost Teeth
- [ ] Ruptured Spleen
- [ ] Broken Ribs
- [ ] Fractured Arm
- [ ] Fractured Leg

Difficult
- [ ] Skull Fracture
- [ ] Concussion
- [ ] Torn Stomach
- [ ] Sucking Chest Wound
- [ ] Compund Arm Fracture
- [ ] Compund Leg Fracture

Deadly
- [ ] Separeted Spine/Decapicated
- [ ] Damaged Eye
- [ ] Heart Damage
- [ ] Septic Shock
- [ ] Dismembered Arm
- [ ] Dismembered Leg
