### ISSUE TITLE
Elderfolk Weapons and Elderfolk Armors inventory tab

### ISSUE THREAD

**Issue by pedroaugustobt** [Stexinator/TheWitcherTRPG#126]
Elderfolk Weapon and Elderfolk Armor are reversed in the diagrams, when I drag an Elderfolk Weapon diagram it is placed in the Elderfolk Armor Diagrams tab, the same happens with Elderfolk Armor.

**Comment by moliloo** [comment]
I've test this bug and works well for me
| Diagram Section |
|--------|
| ![](https://media.discordapp.net/attachments/725195811096363090/1248423881899900971/image.png?ex=66639cd8&is=66624b58&hm=3f6ad9098bf54a9eca1d28eaa86d05249f9574472af7dbbc920229c59c3cf058&=&format=webp&quality=lossless&width=550&height=265) | 

But i notice some bug in image size, maybe a problem with the container and the diagram look like this now
| Diagram Standard Size | Diagram Total Size |
|--------|--------|
| ![](https://media.discordapp.net/attachments/725195811096363090/1248422763954176120/image.png?ex=66639bcd&is=66624a4d&hm=554c6c0e1c727946be915463deee0cfd9f6118768a3af7e8975d1c51c970fb67&=&format=webp&quality=lossless&width=379&height=350) | ![](https://media.discordapp.net/attachments/725195811096363090/1248422854958120980/image.png?ex=66639be3&is=66624a63&hm=b4f284334e69e621225ac4a5c4eb6f2e1f8e43a3eb50603fa18b82351b19f51f&=&format=webp&quality=lossless&width=241&height=350) |

**Comment by pedroaugustobt** [comment]
@moliloo It fixed the bug in the last update of the dev branch

**Comment by moliloo** [comment]
my bad, i just see the tag and the issue open and go to test the sistem

**Comment by Stexinator** [comment]
@moliloo I cannot reproduce the too large image. It seems you dont have the new css. Did you test it on the live version or the dev branch?

**Comment by moliloo** [comment]
The dev branch @Stexinator

**Comment by Stexinator** [comment]
Can you export the item and if it is on an actor also the actor?

**Comment by moliloo** [comment]
where can i send you the export?

**Comment by pedroaugustobt** [comment]
> I've test this bug and works well for me
> 
> Diagram Section
> ![](https://camo.githubusercontent.com/6f89e4dc72a9166ffe17db760659f2d132fe0ef44cd1a1dab55986f19a96e24e/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3732353139353831313039363336333039302f313234383432333838313839393930303937312f696d6167652e706e673f65783d36363633396364382669733d363636323462353826686d3d33663661643930393862663534613965636131643238656161383664303532343966393537343437326166376462626339323032323963353963336366303538263d26666f726d61743d77656270267175616c6974793d6c6f73736c6573732677696474683d353530266865696768743d323635)
> But i notice some bug in image size, maybe a problem with the container and the diagram look like this now
> 
> Diagram Standard Size	Diagram Total Size
> ![](https://camo.githubusercontent.com/d4a040215d84b18af0f432cf31b8c565bbfd5fbe5a1b31178f8c72fcf68babd2/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3732353139353831313039363336333039302f313234383432323736333935343137363132302f696d6167652e706e673f65783d36363633396263642669733d363636323461346426686d3d35353463366330653163373237393436626539313534363364656565306366643966363131383736386133616637653839373564316335316339373066623637263d26666f726d61743d77656270267175616c6974793d6c6f73736c6573732677696474683d333739266865696768743d333530)	![](https://camo.githubusercontent.com/d27f55e5084d7d442fa186ab206b0beaeafdca0665c616e6a22f99f38d0f7643/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3732353139353831313039363336333039302f313234383432323835343935383132303938302f696d6167652e706e673f65783d36363633396265332669733d363636323461363326686d3d62346632383433333465363965363231323235616334613563346562366632653166386534336133656235303630336661313862383233353162313966353166263d26666f726d61743d77656270267175616c6974793d6c6f73736c6573732677696474683d323431266865696768743d333530)

This error happened to me, at first it was about Foundry versions, I updated to v12 and it resolved

**Comment by Stexinator** [comment]
> where can i send you the export?

You can attach them in this issue

**Comment by moliloo** [comment]
```
{
  "name": "Elderfolk Weapon",
  "type": "diagrams",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "description": "",
    "quantity": "1",
    "weight": 0,
    "cost": 0,
    "isHidden": false,
    "isStored": false,
    "type": "elderfolk-weapon",
    "level": "novice",
    "isFormulae": false,
    "craftingDC": 0,
    "alchemyDC": 0,
    "craftingTime": "",
    "investment": 0,
    "learned": false,
    "craftingComponents": [],
    "alchemyComponents": {
      "vitriol": 0,
      "rebis": 0,
      "aether": 0,
      "quebrith": 0,
      "hydragenum": 0,
      "vermilion": 0,
      "sol": 0,
      "caelum": 0,
      "fulgur": 0
    },
    "associatedItemUuid": ""
  },
  "effects": [],
  "folder": null,
  "flags": {
    "exportSource": {
      "world": "tw-rework-amor-test",
      "system": "TheWitcherTRPG",
      "coreVersion": "11.311",
      "systemVersion": "1.034"
    }
  },
  "_stats": {
    "systemId": "TheWitcherTRPG",
    "systemVersion": "1.034",
    "coreVersion": "11.311",
    "createdTime": 1717717547794,
    "modifiedTime": 1717717757229,
    "lastModifiedBy": "Okqi1J8fJgE5Hbio"
  }
}
```

**Comment by Stexinator** [comment]
I cannot reproduce it. You could try to update to the latest foundry v11 version
