### ISSUE TITLE
Crushing Force Effect

### ISSUE THREAD

**Issue by pedroaugustobt** [Stexinator/TheWitcherTRPG#130]
In Witcher Journal, there is a type of damage called Crushing Force, where it has the same effect as Ablation, but the roll formula instead of being 1d6/2 will be 2d6/2.

Can be increased in the future.

**Comment by Stexinator** [comment]
It is always helpful when you add the book and page for new features

**Comment by pedroaugustobt** [comment]
> It is always helpful when you add the book and page for new features
> 
> Witchers Journal - Page 12
> 
> ![grafik](https://private-user-images.githubusercontent.com/69796777/337969847-dd3ec3a1-d70c-4713-90d7-e0c266c6e04b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTk2ODUsIm5iZiI6MTcxNzk1OTM4NSwicGF0aCI6Ii82OTc5Njc3Ny8zMzc5Njk4NDctZGQzZWMzYTEtZDcwYy00NzEzLTkwZDctZTBjMjY2YzZlMDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE4NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NTEzMWI5YWVjYmJkNDA4ZThkZjEwNzk1ZTVmNTk4ZjBmYTU5MWQxOGI4YmFiODE0MzNhNjg1ZTI2Njk1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEj8uMwRlhiU4LPw27k5iv9PC4TH8qGv6E-ooCCZC6s)
> 
> Double ablation damage should be (1d6/2+1) *2 which would have a different spread then (2d6/2 +1)

My bad, when I'm going to refer to something in the book I'm going to do that!
