### ISSUE TITLE
Verbal Combat Damage

### ISSUE THREAD

**Issue by pedroaugustobt** [Stexinator/TheWitcherTRPG#131]
I found a bug in the last update, where the moment I apply damage from verbal combat, this occurs:
![image](https://github.com/Stexinator/TheWitcherTRPG/assets/107325727/a2fa68aa-1a70-403c-ae1c-ea53c0e0373f)

Damage is not applied to Resolve.

**Comment by Stexinator** [comment]
Ah yeah, that happened because I found the bug in the middle of refactoring and fixed that first :( I fix it
