### ISSUE TITLE
Critical Wound have decimals

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#135]
When some critical wounds half or quarter skills or stats, they apply decimals rather than rounding down.

**Comment by Stexinator** [comment]
Rounding at a the correct place would require to implement the Rolls my own. Due to it only being a visual issue this has currently low priority

**Comment by Stexinator** [comment]
If someone want to tackle this:

- Create a own Roll class
- Re-wire everything to use this class
- Add in the calls that the total is rounded
