### ISSUE TITLE
Glyph Of Reinforcement Not Applying Effects To Armour

### ISSUE THREAD

**Issue by Godsassassin007** [Stexinator/TheWitcherTRPG#14]
So now that the armour can actually use enhancements on armour (thank you for the quick fix on that, greatly appreciated) I've noticed that Glyphs don't actually apply their effects (also don't actually take up the EN spot on the armour). I know for some of them that would be hard to do. But for the reinforcement one it basically is just like the steel upgrade so I don't see why it wouldn't work the same. Although I am not a programmer so I may be very wrong.

![Bug3](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/5980445b-c767-4588-94a6-3441ebfdb6c7)

**Comment by Stexinator** [comment]
This works without issue. In your screenshot it seems like you did not apply the EN. Click on the empty square to apply it.

![grafik](https://github.com/Stexinator/TheWitcherTRPG/assets/69796777/bdf4c53b-5a73-415e-921a-039f02632e88)

Armor with 0 SP and enhancement with 3 SP

**Comment by Godsassassin007** [comment]
> This works without issue. In your screenshot it seems like you did not apply the EN. Click on the empty square to apply it.
> 
> ![grafik](https://private-user-images.githubusercontent.com/69796777/312354471-bdf4c53b-5a73-415e-921a-039f02632e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTYyNzQsIm5iZiI6MTcxMDMxNTk3NCwicGF0aCI6Ii82OTc5Njc3Ny8zMTIzNTQ0NzEtYmRmNGM1M2ItNWE3My00MTVlLTkyMWEtMDM5ZjAyNjMyZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA3NDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMzdiNDQyNjdkYWU4ZDIyZTNmYmY1NmU3ODcwZDAwMmVhNDYzMTUxZWMyMDU3MjViYzg5MmM2MzY0NzZkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1jFPSHZNN5YiBOZ0pP0wUMtR_x2Gp5_IJ8CYYf46-NA)
> 
> Armor with 0 SP and enhancement with 3 SP

I did apply it via the EN square. I clicked it then choose the glyph. It adds the flavor text to the armor piece but not the SP. Maybe because I'm using a glyph from the other compendium it isn't applying correctly?

**Comment by Stexinator** [comment]
It has to look like this

![grafik](https://github.com/Stexinator/TheWitcherTRPG/assets/69796777/d1685d64-488b-44ab-858b-ba6e70ded41a)

**Comment by Godsassassin007** [comment]
Yeah mine doesn't look like that. It looks like this

![Screenshot_20240313_044932_Firefox](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/bdfe4d3a-82f1-4184-bb64-d299e0775d61)

And when I apply it the box stays empty and no SP is added but the text is applied to the armor. Must be because I'm using the outside compendium.

**Comment by Stexinator** [comment]
Simply change it from glyph to armor for the effect. I take a look why glyphs are not displayed
