### ISSUE TITLE
Fear Status Icon

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#146]
The feared condition doesn't have a token icon

**Comment by Siryphas** [comment]
![Screenshot (156)](https://github.com/Stexinator/TheWitcherTRPG/assets/144486761/0c4222f6-72a2-49d3-b7ca-32c239988b54)
We only have the one, and it's the Hallucination Icon. Could it be an issue with them using the same icon?

**Comment by Stexinator** [comment]
Do you use condition lab and configured special behaviours? In this case it saves the statuses you had when you configured it and overwrites the system statuses

**Comment by Stexinator** [comment]
If you got an alternative icon for hallucination feel free to post it :)

**Comment by AlexanderTheGr3at** [comment]
> Do you use condition lab and configured special behaviours? In this case it saves the statuses you had when you configured it and overwrites the system statuses

Conditions labs?? What is that!?

**Comment by Stexinator** [comment]
https://foundryvtt.com/packages/condition-lab-triggler

**Comment by Siryphas** [comment]
I do not use Condition Labs

**Comment by Stexinator** [comment]
I can reproduce it on v11. Might well be the image. Do you have an alternate art for hallucination?

**Comment by Siryphas** [comment]
I'll look through some icons and see what I can find

**Comment by Davrill** [comment]
Cheers for including this as an effect - I don't think there are any rules for Fear, bar what has been home brewed via Reddit? Happy to post what we use in our game here, if that's useful? Or for a Wikki?

**Comment by pedroaugustobt** [comment]
> Cheers for including this as an effect - I don't think there are any rules for Fear, bar what has been home brewed via Reddit? Happy to post what we use in our game here, if that's useful? Or for a Wikki?

It doesn't actually exist, but fear is mentioned in Tome of Chaos, 74, theres a Minor Gift called Fear Aura, which says that Fear adds a -2 to all actions against you, @Siryphas gave me this information

**Comment by AlexanderTheGr3at** [comment]
Issue moved to new repo
