### ISSUE TITLE
Automated Animations

### ISSUE THREAD

**Issue by pedroaugustobt** [Stexinator/TheWitcherTRPG#149]
An error is happening in a module called Automated Animations, I activated the debug and in 'attackSkill' and 'damage' it is undefined.
I don't know if this error is on the system side, or on the module side, but I saw people using it normally in DnD
```
actorId: "QEYKEiww9PJVtyks"
alias: "Geralt de Rivia"
attackSkill: undefined
damage: undefined
extraNames: ['no-damage']
item: {name: 'no-damage'}
overrideNames: []
sceneId: "D3zNJUotc4ZKcOjr"
spell: undefined
targets: []
token: TokenDocument {name: 'Geralt de Rivia', displayName: 30, actorId: 'QEYKEiww9PJVtyks', actorLink: true, #validationFailures: {…}, …}
tokenId: "PE9RABR2mp5psViB"
workflow: ChatMessage {type: 'base', system: {…}, style: 0, timestamp: 1719182496336, #validationFailures: {…}, …}
[[Prototype]]: Object
```

**Comment by Stexinator** [comment]
As you can check [here](https://github.com/otigon/automated-jb2a-animations/blob/main/src/system-support/aa-TheWitcherTRPG.js) the module has specific handling for the system. The problem is that the flags were done in a way that is ill-advised following v11+. So I changed that. In the module it still checks for the old way

**Comment by pedroaugustobt** [comment]
I believe there are few changes, can you tell me which type of flags you changed to?

**Comment by Stexinator** [comment]
https://github.com/Stexinator/TheWitcherTRPG/blob/main/module/actor/mixins/itemMixin.js#L591

**Comment by Stexinator** [comment]
@pedroaugustobt will you fix that or can I start with it?

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt will you fix that or can I start with it?

I haven't started yet, but I plan to start now

**Comment by Stexinator** [comment]
I have fixed it locally. I am waiting for some answers and then it can be tested

**Comment by pedroaugustobt** [comment]
> I have fixed it locally. I am waiting for some answers and then it can be tested

Could you send me the file?

**Comment by Stexinator** [comment]
https://github.com/otigon/automated-jb2a-animations/pull/702
