### ISSUE TITLE
Book Of Tales NPC's No Longer In Compendium

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [Stexinator/TheWitcherTRPG#150]
There were there when I checked about 2 weeks ago. Now they are gone. Were they purposely removed?

**Comment by Stexinator** [comment]
For compendium it is best to ping @Siryphas :)

**Comment by Siryphas** [comment]
The NPCs were not intentionally removed. I've got a Compendium update coming hopefully within the next week or so, I'll make sure they're still included.

**Comment by AlexanderTheGr3at** [comment]
> The NPCs were not intentionally removed. I've got a Compendium update coming hopefully within the next week or so, I'll make sure they're still included.

Fantastic!
