### ISSUE TITLE
Linking Global Modifier Items to Spells via drag and drop

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#152]
I'm not sure if I'm missing something, but I've been working on adding Global Modifiers for Spells like Blemish and Glamour, so that when a character casts it, the Global Modifier is added, but the Spell Item doesn't seem to accept the Global Modifier Item if it's dragged onto the sheet. Is this a bug, or is the feature not implemented? If it's not implemented, then how do I make use of the Global Modifier sections at the bottom of the Spell Item page?

**Comment by Stexinator** [comment]
Currently it works with name matching. So currently you simply write the name into it

**Comment by Siryphas** [comment]
Oh, okay, I'll try and see if it works

**Comment by pedroaugustobt** [comment]
> How does this work precisely? Does it need to be in a certain Compendium or Folder? Or already in the PC's sheet?

Yes, it needs to be in the Global Modifiers & Conditions compendium, you create your effect within this compendium and attach the name of the effect to your spell, when you use it it will go to the character sheet that used it.
