### ISSUE TITLE
Variable Damage depending on difference

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#153]
Some spells, like Cenlly Graig, have variable damages based on how much the roll exceeded the target's defense. Is there a way to incorporate this into the system?

"Cenlly Graig hurls sharp stones at your opponent. For every point you roll above your opponent’s defense (maximum 10) you deal 1d6 damage."

Meaning if you beat them by one point you'd do 1d6 damage, but if you beat them by ten or more points, you'd do 10d6 damage.

**Comment by AlexanderTheGr3at** [comment]
This would also fall into the "Damage Roll Pop Up" issue on new repo
