### ISSUE TITLE
Global Modifiers in Templates

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#154]
I'm not sure if it's possible, but is there a way to assign Global Modifiers to Spell Templates, so that if a token is within the Template area, they are subject to the effect of the Spell, and when they leave it, they are not?

**Comment by pedroaugustobt** [comment]
Eu uso um modulo atualmente para fazer isso que se chama Monk's Active Tile Triggers, ele deixa você criar um modelo e fazer ações. Como você pode ver aqui, criei o yrden:
![image](https://github.com/Stexinator/TheWitcherTRPG/assets/107325727/f6022c9f-9748-465d-be2f-4f98d67487d3)
Here I set "Enter, Exit" for when the token enters and exits
![image](https://github.com/Stexinator/TheWitcherTRPG/assets/107325727/d8a27a88-2219-4e18-a4b7-a42e35f84f7d)
And in the actions I defined that an effect would be applied to the triggered token.
Detail: You need to create an effect called yrden with CUB. I'm checking the possibility of making a macro that automates all of this.
![image](https://github.com/Stexinator/TheWitcherTRPG/assets/107325727/2441014b-5f8e-4bda-b5a1-466cf257d0d1)

**Comment by Siryphas** [comment]
Can you attach this to Spells though? So when a Spell is cast that has a Template, it applies this effect?

**Comment by pedroaugustobt** [comment]
Not currently, but at least you can create a preset to help, but you'll have to put it on the canvas manually.
I'm looking into the possibility of creating a macro so that when I cast the spell, automatically place the tile.

**Comment by AlexanderTheGr3at** [comment]
Issue moved to new repo
