### ISSUE TITLE
Fixed Stats as Global Modifiers

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#155]
At the moment, it appears that we can only + or - Stats using Global Modifiers, but there are a few instances where a Stat is set to a defined number, such as a side effect of Elgan's Bastion:
_"Created by the famed magician Elgan of Verden, Elgan’s Bastion uses trace amounts of metal in stone to magnetically lift a shield of rocks around you to defend yourself from physical attacks and damage. 
This shield of rocks counts as a Cover with 30 SP and entirely surrounds you.
While surrounded, your SPEED Statistic cannot be higher than 2 and you cannot do anything on your turn but take a single Movement Action."_
Ideally, we'd be able to set a Global Modifier for this spell that sets a character's SPD Stat at 2 rather than having to custom tailor each modifier to each character's individual SPD stats.

**Comment by Stexinator** [comment]
You can also /

I could add < to force a stat to be smaller then the number

**Comment by Siryphas** [comment]
> You can also /
I'm not sure what this means.

**Comment by Stexinator** [comment]
You can do simple math like dividing. The operations are hard coded but I can enhance that

**Comment by Siryphas** [comment]
Yes, but there's a difference between dividing a stat and setting a stat to a static value. If a spell or condition sets a character's SPD to 2, it defeats the point of automation to have to manually calculate the subtraction or division of the stat to reach the desired value.

**Comment by Stexinator** [comment]
Yes, this was an example. The bastion says that the speed can not be higher then 2 and does not set it to 2.

Thats why I suggest to add a "<" so that the last check would be that after everything is calculated the result is smaller then the number to the right
