### ISSUE TITLE
Damage that bypasses SP

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#156]
There are several sources of damage in the system that can bypass SP. Poison, Bleeding, Magical Fumbles, as well as the effects of certain spells, such as Javad's Swarm:
_"Upon casting this spell, a swarm of controlled insects crawls out from nearby crevices and forms a horde with a SPD Statistic of 7 which can engulf a single target by making an attack at a Base 14. 
This attack deals 1d6 damage to the target’s torso, **ignores all worn armor**, and has a 100% chance of poisoning. 
The Horde has 15 Hit Points and a Dodge base of 14."_
Is there a way to have this added to Global Modifiers, Weapons, and Spells? I'll likely be making Javed's Swarm a Bestiary entry with weapons that can be added by the GM when the spell is cast, but it would be nice for this to be a versatile feature.

**Comment by Stexinator** [comment]
So, this does not bypass natural armor which makes it more complicated

**Comment by Siryphas** [comment]
True, but Poison and Bleeding do.
