### ISSUE TITLE
Aard - Staggered % = 10%/sta

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#159]
The percentage for conditions doesn't allow for the use of %/sta as it does with damage. Any chance we can get that added?

**Comment by Stexinator** [comment]
Does this apply only to spells with variable stamina?

Does this apply to all spells with variable stamina?

**Comment by Siryphas** [comment]
I believe it only applies to Spells with Variable STA, but I'm not sure if it applies to all Spells with Variable STA. But if we were able to input %/STA the same way we can input 1d6/STA for damage, I'd be able to include it in the Compendium for all Spells/Signs that it does apply to.

**Comment by Stexinator** [comment]
For the calculations I need it to be a number, thats why the type is strict now. If you aint sure I always can add a checkbox to flag that the % also scales with STA

**Comment by Siryphas** [comment]
That would work. The only Magic I know 100% that has this at the moment is Aard. But as long as there's someway to scale it so that 1 STA does 10%, 2 STA does 20%, etc. It'll be fine.
