### ISSUE TITLE
[Long Term Goal] Global Modifiers - Cause Damage

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#161]
In an effort to apply conditions like Bleeding, Poison, Fire, etc. is there a way we can have Global Modifiers apply Damage? There would have to be two types of Damage: SP Damage and Non-SP Damage. Fire for example is reduced by SP, but ablates all Equipped armor by 1 each round. Bleed and Poison are not reduced by SP, so there would need to be a way to do damage straight to HP, bypassing an actor's SP.

**Comment by Stexinator** [comment]
This is currently far away. For this to work the system would need an ingame time tracking possibility. Then it needs to react to time passing. Both things are large features that I cannot do alone. Someone might join in and work on this stuff dedicated

**Comment by Siryphas** [comment]
Understood

**Comment by AlexanderTheGr3at** [comment]
Adding in: Items like "White Raffard's Decoction"  are suppose to heal 1hp per round, but as it is it only heals 1hp total. So as well as needing Global modifiers to do damage, we need them to do/track healing as well.
