### ISSUE TITLE
Dice so Nice problem

### ISSUE THREAD

**Issue by pedroaugustobt** [Stexinator/TheWitcherTRPG#165]
There is a problem with the Dice so Nice module that when it is critical or fumble, the dices from the module does not appear, the result is printed directly in the chat, is there a possible resolution for this?

**Comment by Stexinator** [comment]
@ortegamarcel had a fix for that. But it never made it to the main repo, so it is not included here. @ortegamarcel would you be willing to add your fix to this fork?
