### ISSUE TITLE
Character Sheet Top is showing differently

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#167]
I'm not sure if it's a feature or a bug, but the top of the Character Sheet is extremely condensed and has a lot of empty space as compared to the previous version.

**Comment by pedroaugustobt** [comment]
> I'm not sure if it's a feature or a bug, but the top of the Character Sheet is extremely condensed and has a lot of empty space as compared to the previous version.

A remastering of the sheet layout is being carried out, I believe that in the next commits there will be a visual improvement for the users
