### ISSUE TITLE
Investigation Clarification

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#168]
Not an issue per se, but I'm not sure how the Investigation system is supposed to work. I can't figure out how to allow the players to roll Evidence checks against the Mystery. Can we get some documentation or a revision of the system mechanics.

**Comment by Stexinator** [comment]
In the current state you can create a mystery and configure clues and obstacles. You can show/hide clues and obstacles from the player.

**Comment by Siryphas** [comment]
How do the players roll the Evidence Checks? From the Mystery page?

**Comment by Stexinator** [comment]
The mysteries have no automation

**Comment by Siryphas** [comment]
Is there a chance we could get automation in the future?

**Comment by Stexinator** [comment]
Sure thing, just create issue for it :)

I didnt use it yet so I dont know what is needed
