### ISSUE TITLE
Make item consumable

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#172]
As title

- Check which items should be consumable
- Check if new item class is needed
- add context menu https://foundryvtt.wiki/en/development/api/application#contextmenu
- ???
- profit

**Comment by AlexanderTheGr3at** [comment]
Here's a list of the item's I'm 99% sure are consumed upon use. Take a look over it and see if I missed anything/added something that isn't supposed to be there.

**Elixirs:**
- Anabolic Steroids
- Last Hope
- Lightning
- Mongoose
- Strider
- Tempest

**Mundane Potions:**

- Vitality Potion
- Endurance Potion
- White Raffard's Decoction

**General Gear:**

- Bag of Marbles
- Jar of Leeches
- Pitons (x5)
- Muzzle
- Vial of Gut Worms
- Dwarven Whetstone
- Trail Rations
- Sweets
- Raw Meat
- A Feast
- A Good Meal
- A Simple Meal
- Alcohest
- Beer
- Spirits
- Wine

**Witcher Potions:**

- Black BLood
- Blizzard
- Cat
- Full Moon
- Golden Oriole
- Killer Whale
- Maribor Forest
- Petri's Filter
- Swallow
- Tawny Owl
- Thunderbolt
- White Honey

**Witcher Decoctions:**

- Arachas
- Fiend
- Grave Hag
- Griffin
- Katakan
- Nekker
- Noon Wraith
- Troll
- Werewolf
- Wyvern

**Blade Oils:**

- Beast Oil
- Cursed Oil
- Draconid Oil
- Elementa Oil
- Hanged Man's Venom
- Hybrid Oil
- Insectoid Oil
- Ogroid Oil
- Relict Oil
- Specter Oil
- Vampire Oil

**Bombs:**

- Dancing Star
- Devil's Puffball
- Dimeritium Bomb
- Dragon's Dream
- Grapeshot
- Moon Dust
- Northern Wind
- Samum
- Zerrikanian Sun
 
**Traps:**

- Clawer
- Conflagration
- Fury
- Marker
- Talgar Winter

**Ammo:**

- Explosive
- Split
- Tracking
- Blunt
- Bodkin
- Broadhead
- Standard
- Scorpio Bolts Breaker Bolt
- Scorpio Bolts Piercing Bolt
- Scorpio Bolts Standard Bolt

**Comment by Stexinator** [comment]
For now I added a simple checkbox to mark items as consumable. Automation will follow later

**Comment by Stexinator** [comment]
@AlexanderTheGr3at you listed some items where I am very positive that they cannot be consumed. I want to differentiate between using an item and ingesting or applying it.
