### ISSUE TITLE
Investigation System Automation

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#174]
The Investigation System, like Verbal Combat, is a type of encounter. Evidence checks are made by the players as a form of attack against the Mystery's HP, called Complexity. Each clue can have an Obfuscation rating, which works like SP, reducing the damage done by a PC's Evidence check. There are also Obstacles which are things the players must overcome. Obstacles force the PCs to come up with their own solutions, so they can use any Skill to overcome them. If they succeed, they take 2 points of Focus damage (Focus being the Player's health in the Investigation, like Resolve in Verbal Combat). If they fail to beat the obstacle, they take 1d6+2 Focus damage. 

Players need to be able to roll for their Evidence Checks using the Skills listed for each type. They need to be able to roll damage based on the type of Evidence Check (1d10+INT, 1d6+EMP, 1d6+WILL, etc.). The damage needs to be able to be applied to the Mystery's Complexity and have the Obfuscation score subtracted from the damage. If they fail the Evidence Check, it deals Focus damage to the players, and that damage should be able to be applied to their Focus. Whether they succeed or fail to overcome an Obstacle, they will also take Focus damage. Whether it's a flat 2 points or 1d6+2, it should be able to be applied to their Focus values.

All of this information is in _A Witcher's Journal_ starting on page 145.

**Comment by Stexinator** [comment]
Can you create one issue per feature? e.g. "rolling evidence checks" is one feature, "applying damage" is a second etc.

In the issue it would also be nice to reference screenshot of the existing sheet and mark where the data comes from and how do you want to trigger a roll
