### ISSUE TITLE
Glyph Now Applies To EN Slot But Doesn't Add Effect

### ISSUE THREAD

**Issue by Godsassassin007** [Stexinator/TheWitcherTRPG#18]
So I have my armour and my glyph.

![1](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/1fe23509-3aff-4cf7-a645-54c928e50a2b)

I can select it through the EN slot now.

![2](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/a24c9db9-e1ab-4775-8954-24d6ed6239cc)

It applies the glyph, removes it from the glyph category down below and displays in the EN box. What it doesn't do is actually add the 3 stopping power to the armour. Fixable? Or something we'll have to do manually? I know most of the glyphs have effects that can really be "applied" per say.

![3](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/4faad157-b9ce-4a0c-b993-f41679304b96)

**Comment by Stexinator** [comment]
Either you change the type from "glyph" to "armor" so the system picks the 3 SP up or you have to do it manually.

**Comment by Godsassassin007** [comment]
> Either you change the type from "glyph" to "armor" so the system picks the 3 SP up or you have to do it manually.

Okay sounds good. Thanks for the help. Now I just need to figure out how to add the compendium to my branch lol.

**Comment by Stexinator** [comment]
I had a talk with Siryphas. He will supply me with his updated compendium soon

**Comment by Godsassassin007** [comment]
How did you manage to get in touch with him?

**Comment by Stexinator** [comment]
I searched his handle in discord

**Comment by Godsassassin007** [comment]
Smart. I don't use Discord so I never would have thought of that. So are you going to incorporate his most updated version?
