### ISSUE TITLE
Alzur's Thunder - Declining Damage

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#180]
WTRPG Core Rulebook, Page 106
![Screenshot_20240710_015810_Adobe Acrobat](https://github.com/Stexinator/TheWitcherTRPG/assets/144486761/efb644f5-a778-4953-a2e5-786cbe7cd47d)

**Comment by Rada848** [comment]
This would also be useful with spells that do scaling damage like Cenlly Graig and Carys’ Hail, as I'm not sure how to get them to work.

**Comment by Stexinator** [comment]
@Rada848 for this there is https://github.com/Stexinator/TheWitcherTRPG/issues/153

**Comment by Rada848** [comment]
Ahh I'm sorry, I must have overlooked it while looking to see if it had already been brought up.

**Comment by Siryphas** [comment]
> If this is the only spell that behaves that way, automating it will not happen for a long time

It is the only spell to my knowledge, however, having run four Witcher games over the course of 3 ½ years, it's by far one of the most used Spells of any listed in the system.

**Comment by Stexinator** [comment]
Can you write down and possible add screenshots/mockups how you imagine it to work?

**Comment by Siryphas** [comment]
> Can you write down and possible add screenshots/mockups how you imagine it to work?

I don't really know coding, but maybe if the Roll Damage button asked how many d6/d10's it rolls? It could default to the number listed in the damage, but allow it to be changed, each time the Damage button was clicked by the GM or players.

**Comment by AlexanderTheGr3at** [comment]
I think this one is covered in the "Damage Roll Pop Up" issue in the new repo
