### ISSUE TITLE
Completly rework silver damage

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#182]
There are several flaws in the code regarding silver damage.

In version 1.042 silver is halved when the monster is resistant to ``non-silver damage``. This is wrong.

The current fix is to half everything but the rolled silver damage but this has some side-effects with ``resists non-meteorite`` => Silver would apply full to it

**Comment by AlexanderTheGr3at** [comment]
Moved to new repo
