### ISSUE TITLE
Fork closing down

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#185]
Development will continue at https://github.com/witchertrpg-foundryvtt/witchertrpg

**Comment by Siryphas** [comment]
Are all of the Issues being transferred, or will we need to reopen all the current Issues on the new page?

**Comment by Stexinator** [comment]
The issues need to be transfered by hand. I would like some help with that :) Please close any issue you copied over

**Comment by AlexanderTheGr3at** [comment]
> The issues need to be transfered by hand. I would like some help with that :) Please close any issue you copied over

Is it possible to close issues I didn't open? Because if so I'll move them all over.

**Comment by Stexinator** [comment]
Unfortunately not. But if you post them here I can close them
