### ISSUE TITLE
[HELP WANTED] Looking for an UX designer to improve layout and looks

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#21]
If you are interested in helping with the layouting and look and feel of the system please comment below

**Comment by shadows-eye** [comment]
I might help, not sure yet if I have the time and I don't know the game so that limits the help I can provide 😄

**Comment by MrOzymandyas** [comment]
I have a shared Figma file with two friends for this project. We're all amateur UX/UI designers, but we've been experimenting and refining the system with various groups for years now. I'll let you know when we have something a bit more solid to share.

**Comment by MrOzymandyas** [comment]
We are still working on the skeleton. Work been eating us up. The shield is a good suggestion tho, we will try to work with that in mind.

**Comment by Stexinator** [comment]
@MrOzymandyas any news? I got the next feature where I need some UX input :) Applying the results of crits

**Comment by moliloo** [comment]
i have been working in a character sheet for a while and i want to sent to you for see how its going in your discord, when you want accept my solicitation i will send you the link of figma file, the sheet is a prototype, i need make some style later, but i want your feedback

**Comment by pedroaugustobt** [comment]
> i have been working in a character sheet for a while and i want to sent to you for see how its going in your discord, when you want accept my solicitation i will send you the link of figma file, the sheet is a prototype, i need make some style later, but i want your feedback

Can you send it to me too? I can help with the front

**Comment by Stexinator** [comment]
There is a discord group for improving the UX. If you want to take part write me your discord handle and I add you
