### ISSUE TITLE
Long text fields put in indentation for no reason after any change done to them

### ISSUE THREAD

**Issue by thenotsogrim** [Stexinator/TheWitcherTRPG#25]
First of all, thanks for continueing the work on this system, it means a lot to me!

Inexplicably any long text fields will put a huge indentation after the first line on several long text fields. I'm not sure if there's a global text editing going on, but it makes a lot of the sheets a hassle to use, not to mention it puts little faith in the system by the players. When I keep editing a field like this, trying to remove these indentations, the system just puts in another instance of the indentation.

![image](https://github.com/Stexinator/TheWitcherTRPG/assets/132756970/2c16ae83-da85-4dd4-b339-e9928aa79fe2)

**Comment by Stexinator** [comment]
The next update will kind of fix it. There will be new notes where this will not happen anymore. If I get around it I will migrate the old notes to the new ones, but this will not be included yet. You can manually copy your data if you want.

**Comment by Stexinator** [comment]
The update is live
