### ISSUE TITLE
Improve visibility of option to deselect/hide all skills for Monsters, and ability to select which skills should show in the monster sheet

### ISSUE THREAD

**Issue by thenotsogrim** [Stexinator/TheWitcherTRPG#26]
To facilitate quicker creation of Monsters it would be better to have an option to deselect/hide all skills, and then give the option to enable which skills each Monster should have.

If that's not possible, then could the skills be changed to an alphabetical list instead of a categorised list based on Attributes? Both the Core Rulebook and the Witcher's Journal merely lists any relevant skills a monster may have in an alphabetical order which makes it a bit easier to see what skills are relevant to a monster at a glance. 

Currently setting up any creature would take at least 10 minutes with quick copy-pasting - and there's dozens of them in the two books.

![image](https://github.com/Stexinator/TheWitcherTRPG/assets/132756970/1bdb70a9-9e7b-4073-805f-95bcaefb12c0)

**Comment by Siryphas** [comment]
You can already hide/show skills. Just left of the Initiative button is a three-line (hamburger) menu, if you click that, it lets you toggle which skills show up and which ones don't.

**Comment by thenotsogrim** [comment]
Ah okay, so I found it, but is it really supposed to be up here on the left? I would've never found it if you hadn't told me it's there.

![image](https://github.com/Stexinator/TheWitcherTRPG/assets/132756970/71662820-12e1-4388-89a2-2e74cba87004)

Anyway, even then, unselecting everything that you don't need is a pain. I'd much rather have all these options deselected, or at least there to be a deselect all button. Most monsters have around 10 skills, having to untick 30ish one by one is hassle. At that point for the 20-30 monsters that exist in the books I'm better off still referencing the pdf instead of making my life easier with the system.

![image](https://github.com/Stexinator/TheWitcherTRPG/assets/132756970/4fd5d422-e689-4726-af03-79ea61316322)

**Comment by Siryphas** [comment]
Well, the good news is that you don't have to. I have a complete compendium. You can find v.1 on Reddit now, and I'm working on v.2, which will be implemented into the system module.

**Comment by Stexinator** [comment]
> Ah okay, so I found it, but is it really supposed to be up here on the left? I would've never found it if you hadn't told me it's there.

That is why I put out the help wanted for UX design. I am not good at it :)

**Comment by Siryphas** [comment]
Adding a Select All/Deselect All button might help this feature
