### ISSUE TITLE
[Feature] Life Paths for Exceptional Monsters

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#35]
Both Higher Vampires and True Dragons have their own Life Path rolls, but there's no place on the Monster Sheets to put them. If possible, could you add a section for Lifepath or create a separate sheet for Exceptional Monsters, whatever is easiest?

**Comment by Stexinator** [comment]
This is in both cases a little bit more complicated. You could do with a character sheet for now. I think in the long term a third sheet type would be best but this needs some more groundwork first

**Comment by Stexinator** [comment]
Can you write everything down that you would need for an exceptional monster that is currently not in the monster?

**Comment by Stexinator** [comment]
Where in the rule books can I find exceptional monsters?

**Comment by Siryphas** [comment]
Exceptional Monsters are in the Witcher's Journal and include the True Dragon and Higher Vampire. Each of them have their own Lifepath rolls. If you could add a Lifepath Sheet to the Monster Actor Sheet or create a new Actor Sheet for Exceptional Monsters, it would be appreciated.

**Comment by AlexanderTheGr3at** [comment]
Issue moved to new repo
