### ISSUE TITLE
[Feature] Add system specific conditions

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#45]
If an attack can apply a condition the chat message should have an drag and dropable icon

Attacks:
- Bleeding
- Staggered

Spells:
- Frozen
- Healing
- Quen

**Comment by Stexinator** [comment]
If possible add automation for immunities

**Comment by pedroaugustobt** [comment]
@Stexinator Do you have discord or another place that could talk to you?
