### ISSUE TITLE
NPC Sheets are broken

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#53]
As of the last patch, NPC sheets are completely broken and unusable. The Skill tabs don't open, the sheets won't track current HP, STA, or Resolve, and the Weapon Attack Menu doesn't pop up when an attack is selected. Hopefully, this can be fixed quickly, as the game cannot be played until this is fixed.

**Comment by Stexinator** [comment]
All reported errors are fixed with 1.014 If you find another you can post it in this issue. If you cannot find any you can close this :)
