### ISSUE TITLE
Token Action HUD module no longer works

### ISSUE THREAD

**Issue by Alkaponer** [Stexinator/TheWitcherTRPG#59]
Token Action HUD module no longer works. It worked with 1.0.12 but has been broken since.

**Comment by Stexinator** [comment]
I get the error that the token hud is to old for core. So you would have to take it to the module maintainer

**Comment by Stexinator** [comment]
https://github.com/ortegamarcel/fvtt-token-action-hud-thewitchertrpg/issues/41

**Comment by Stexinator** [comment]
@Alkaponer In my world the action hud works without issue. Check if you have the latest version
