### ISSUE TITLE
character sheets disappear

### ISSUE THREAD

**Issue by pedroaugustobt** [Stexinator/TheWitcherTRPG#62]
Two of my character sheets disappeared, and this error appears here

![image](https://github.com/Stexinator/TheWitcherTRPG/assets/107325727/31039141-0cf7-419a-b74d-7f3fb29882bc)

**Comment by Stexinator** [comment]
Do you know which bounty you set for them?

**Comment by pedroaugustobt** [comment]
> Do you know which bounty you set for them?

I dont remember, but maybe i didnt value these two

**Comment by Stexinator** [comment]
Can you provide me with an export of these two?

**Comment by Stexinator** [comment]
@pedroaugustobt if you got no news for me I will close this issue end of the week
