### ISSUE TITLE
Trying to control active effects

### ISSUE THREAD

**Issue by MrOzymandyas** [Stexinator/TheWitcherTRPG#64]
I've been attempting to control active effects using the Condition Lab Triggler Module, but all my attempts to guess the correct Attribute Key have failed.

For example, I'm trying to automatically reduce the dodge/escape roll by 2 when a character is dazed.

Using actor.system.skills.ref.dodge.value or WITCHER.SkRefDodge does not work.

Is there a chance it isn't possible at all? If it is, what am I missing?

**Comment by Stexinator** [comment]
I wrote myself a macro for it:

`let actor = arguments[1]

let brawling = actor.system.skills.ref.brawling;
let melee = actor.system.skills.ref.melee;
let smallblades = actor.system.skills.ref.smallblades;
let staffspear = actor.system.skills.ref.staffspear;
let swordsmanship = actor.system.skills.ref.swordsmanship;

let archery = actor.system.skills.dex.archery;
let crossbow = actor.system.skills.dex.crossbow;

let dodge = actor.system.skills.ref.dodge;

if(brawling.modifiers.filter(mod => mod.id === "Staggered").length > 0) {
	console.log("Staggered vorhanden")
	
	brawling.modifiers = brawling.modifiers.filter(mod => mod.id !== "Staggered")
	melee.modifiers = melee.modifiers.filter(mod => mod.id !== "Staggered")
	smallblades.modifiers = smallblades.modifiers.filter(mod => mod.id !== "Staggered")
	staffspear.modifiers = staffspear.modifiers.filter(mod => mod.id !== "Staggered")
	swordsmanship.modifiers = swordsmanship.modifiers.filter(mod => mod.id !== "Staggered")
	archery.modifiers = archery.modifiers.filter(mod => mod.id !== "Staggered")
	crossbow.modifiers = crossbow.modifiers.filter(mod => mod.id !== "Staggered")
	dodge.modifiers = dodge.modifiers.filter(mod => mod.id !== "Staggered")
}
else {
	brawling.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	melee.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	smallblades.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	staffspear.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	swordsmanship.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	archery.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	crossbow.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
	dodge.modifiers.push({id: "Staggered", name: "Staggered", value: "-2"})
}

let ref = 'system.skills.ref';
let dex = 'system.skills.dex';

actor.update({
	[`${ref}.brawling.modifiers`]: brawling.modifiers,
	[`${ref}.melee.modifiers`]: melee.modifiers,
	[`${ref}.smallblades.modifiers`]: smallblades.modifiers,
	[`${ref}.staffspear.modifiers`]: staffspear.modifiers,
	[`${ref}.swordsmanship.modifiers`]: swordsmanship.modifiers,
	[`${ref}.dodge.modifiers`]: dodge.modifiers,

	[`${dex}.archery.modifiers`]: archery.modifiers,
	[`${dex}.crossbow.modifiers`]: crossbow.modifiers
})`

**Comment by Stexinator** [comment]
I created https://github.com/Stexinator/TheWitcherTRPG/wiki/Automating-conditions
