### ISSUE TITLE
[HELP WANTED] Beta testers

### ISSUE THREAD

**Issue by Stexinator** [Stexinator/TheWitcherTRPG#65]
Hey everyone,

I am looking for some beta testers. 

You need to

- be able to exchange code files (preferably from a branch)
- have some good characters to test :)

I plan to write in the feature ticket that it can be beta tested on a certain branch

**Comment by TillTHMAcc** [comment]
Me and a friend would like to help, how i start the project?

**Comment by Stexinator** [comment]
Do you have experiences with git and IDEs?

**Comment by moliloo** [comment]
I would like be a beta tester as well, what will be the branch for tests?

**Comment by Stexinator** [comment]
I created the label beta test. I hope this way you can see on a glance where testing would be nice :)

**Comment by pedroaugustobt** [comment]
I'm willing to test

**Comment by pedroaugustobt** [comment]
I don't have much experience with IDEs, I usually work in Foundry's own environment

**Comment by Stexinator** [comment]
I wrote https://github.com/Stexinator/TheWitcherTRPG/wiki/Beta%E2%80%90Testing-a-feature If you need additional information I can add them to the page. I hope it is already helpful
