### ISSUE TITLE
Natural Armor option on NPC sheets

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#69]
Can we get the option for Normal or Natural SP for Monster/NPC sheets, so that Bandit Armor will ablate as normal, but Monsters won't?

**Comment by Stexinator** [comment]
This can be beta tested on https://github.com/Stexinator/TheWitcherTRPG/tree/feature/rework_armor

**Comment by Stexinator** [comment]
Somewhen I want to rework the monster armor to utilize the same system as player characters but that is not included here

**Comment by Stexinator** [comment]
@moliloo this is a rather small feature. Can you test it after the other story? I want to release it together :)

**Comment by Stexinator** [comment]
This will be done in two steps. The next version allows monsters to equip armor like characters do. After the compendium is switched over to this possibility the current armor of monsters will be converted to natural armor which does not ablate and condensed to one field.

@Siryphas the equipped armor will behave exactly as player armor, so you can configure it like you want :)

**Comment by moliloo** [comment]
I tested this feature and armor in monster is a cool ideia
## Tests
### Feature Works
- Physical and magical damage decrease SP of the armor
- Resistances and vulnerabilities works fine in halve or duplicate the damage
- The SP is summed with the natural armor and gear armor and i don't see problems in the applied damage

### Feature Bugs
- Gear armor, equipped or neither, the natural armor isn't decreased, only the gear amor

**Comment by Stexinator** [comment]
Natural armor does not ablate. So this is expected
