### ISSUE TITLE
Verbal Combat Damage Rolls

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#78]
Add a way to roll damage using Verbal Combat and apply it to a character's Resolve.

**Comment by Stexinator** [comment]
I did not play with verbal combat yet. Can you describe what the system currently supports and what you want to have added in which way?

**Comment by Siryphas** [comment]
It rolls attacks and defenses, and tells you how much damage each does, but it doesn't roll the damage for you like a weapon attack does.
I would like it to roll damage like the weapons attacks, but applying the Verbal Combat damage would need to go to the character's Resolve rather than their HP

**Comment by Stexinator** [comment]
I looked into it and the system also needs a bigger overhaul. So this will take some weeks before I will add new features for it

**Comment by moliloo** [comment]
I tested the verbal combat and everything works fine, selecting the verbal attack and the damages are aplied well in character actor and monster actor, the bonus modifiers works well too, but i have a question, there are fumble or critic on verbal combat? I dont play with this rules and i dont have shure about it

**Comment by Siryphas** [comment]
You can Fumble and Crit like you can with anything, but there's no tables. No Fumble tables or Critical Wounds for Verbal Combat.
