### ISSUE TITLE
Status Condition Icons

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#87]
I've noticed you're working on the Status Effect icons, but many of the default FoundryVTT Icons are missing now, and other icons have been relabeled. For example, the Icon that normally represents Prone is now listed as Staggered, and other interactive Icons like the Invisible Icon are now missing.
I'm pleased that system specific Icons have been added and am hoping that in the future, they'll be interactive conditions (with tokens with the Bleed condition losing 2 HP per turn), but some of the missing tokens are still required.

**Comment by Stexinator** [comment]
Hey,

the system status effects override the default ones. If you are missing status effect please compile an as complete list as possible and I will add them.

**Comment by Stexinator** [comment]
- Unconscious
- Grappled
- Prone
- Flying
- Frightened
- Invisible
- Aiming
- Deaf
- Reduced Vision (from helmets)
