### ISSUE TITLE
weapons enhancements slots

### ISSUE THREAD

**Issue by hollowSkull0** [Stexinator/TheWitcherTRPG#88]
When you add a runestone to a weapons enhancement it causes a bug that when you go to roll to hit with the weapon and press the roll button the roll does not happen and doesn't appear in chat. Also, when you add the runestone it does not appear on the weapons effects table.

**Comment by Stexinator** [comment]
Can you add a screenshot for your runestone and weapon configuration?

**Comment by hollowSkull0** [comment]
![Runestone](https://github.com/Stexinator/TheWitcherTRPG/assets/169599100/c34596b7-092f-4ed6-a884-41c4952c0145)
![steel sword](https://github.com/Stexinator/TheWitcherTRPG/assets/169599100/53247509-5381-4d52-bfe0-93c76b9bdc8c)
![sword](https://github.com/Stexinator/TheWitcherTRPG/assets/169599100/12e3fafa-213b-4fca-8f6b-955f32d810c1)
![console](https://github.com/Stexinator/TheWitcherTRPG/assets/169599100/ca387177-b5fd-4516-beeb-f2c8d9ea9eaf)
