### ISSUE TITLE
[Compendium] Barbegazi HP mismatch

### ISSUE THREAD

**Issue by thenotsogrim** [Stexinator/TheWitcherTRPG#92]
Hi All, this should be a quick one (I don't know if the Compendium related issues should be separated from the github or if it's fine here?)

The Barbegazi is supposed to have 20 HP per "A Witcher's Journal", but in the compendium it is set to 50.

**Comment by Stexinator** [comment]
@Siryphas is handling the compendium. He is currently swamped with other work. Whenever he updates his compendium module he sends me an update to incorporate. I would let it sit here so he might see it

**Comment by Siryphas** [comment]
Yeah, I know there are a couple mistakes. I have most of those edits done, but there are things @Stexinator has been adding to the system that need to go into the Compendium and I'm trying to add additional content, such as Effects for things, like when you cast the Glamour Spell, you can add the effect which will give +3 to the appropriate skills without having to give yourself custom modifiers or manual modifiers.
I also have a couple non-Witcher related projects that have been eating at my time. In the meantime, @thenotsogrim  any small edits like that can be easily changed temporarily until I can get around to it. You can unlock the Compendium package by right clicking it and selecting the option to unlock editing. When I new version of the system comes out, it will revert to the default, but if you just need it for a single session or so, you should be fine to edit it and I'll fix it proper when the next Compendium Update comes out.

**Comment by thenotsogrim** [comment]
Thanks both! Yeah I found a temporary workaround and it's not a major issue, just wanted to add it here in case it was missed.

**Comment by Siryphas** [comment]
> Thanks both! Yeah I found a temporary workaround and it's not a major issue, just wanted to add it here in case it was missed.

Yes! Please, if you find any errors or missing things, report them. I'm only human and do (occasionally) make mistakes. But I like to be thorough, so if anything is out of place I'll add it to the list.
