### ISSUE TITLE
Unable To Drag And Drop From One Player To Another.

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [Stexinator/TheWitcherTRPG#99]
My party has a cart they store all their loot in. As it stands right now I can't seem to drag and drop it in or out of the cart to or from the player. I also can't drag and drop loot for enemies into characters inventory. I can export to the side tabs then "sell" it to the player for 0 crowns to work around it.

**Comment by Stexinator** [comment]
I can drag and drop from loot and other characters without issue.

**Comment by AlexanderTheGr3at** [comment]
I'll see if I can recreate in the morning. 

On a side note I'm working on a very large detailed map as well as a compendium of all the locations. Figured you may want to include them when I'm done.

**Comment by Stexinator** [comment]
Maybe you were confused because the original item is not deleted. It creates a copy of it in the target actor

**Comment by AlexanderTheGr3at** [comment]
> Maybe you were confused because the original item is not deleted. It creates a copy of it in the target actor

Sorry, passing in the family so I got delayed. I was able to drag and drop between players, but still not between "loot" and players. [I've attached a video](https://youtu.be/_NSYhfWdhRY).

**Comment by Stexinator** [comment]
The only thing that you cannot drag and drop from the rows is the image.

**Comment by Stexinator** [comment]
![DragDrop](https://github.com/Stexinator/TheWitcherTRPG/assets/69796777/36ba560b-c381-49b6-bd3c-0a99a4952056)
![DragDrop2](https://github.com/Stexinator/TheWitcherTRPG/assets/69796777/7a8b357f-207c-421d-a6ee-a864960b2316)

Do you get any errors on the console?

**Comment by Stexinator** [comment]
Are you using Firefox or Chrome?

**Comment by AlexanderTheGr3at** [comment]
Yeah, I can't seem to reproduce that. I'm on Firefox. Maybe one of my browser plug-ins is stopping it? I'll try again when I get home and send the console. I'll also try chrome.

**Comment by Stexinator** [comment]
I got new information that non-GM might have an issue. I am looking into that

**Comment by AlexanderTheGr3at** [comment]
> I got new information that non-GM might have an issue. I am looking into that

Sounds good. Let me know if you need anything from me.

**Comment by Stexinator** [comment]
@AlexanderTheGr3at you need to manually switch out the files. You can not update it via foundry until it is released. I suggest you have a separate install/folder for it

**Comment by AlexanderTheGr3at** [comment]
> @AlexanderTheGr3at you need to manually switch out the files. You can not update it via foundry until it is released. I suggest you have a separate install/folder for it

Switched them out and it seems to be working now!
